---
- hosts: webservers
  become: true
  gather_facts: true
  vars:
      war_file_path: /var/lib/jenkins/workspace/maven_nexus/webapp/target/webapp.war
          
  tasks:
    - name: upload file to Nexus
      uri:
       url: " http://{{ nexus_ip }}:8081/repository/maven-releases/"
       validate_certs: no
       method: "PUT"
       status_code: 201, 200, 500
       src: "{{ war_file_path }}"
       url_username: "{{ user }}"
       url_password: "{{ passwd }}"
...



